[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[build]
  command = "npm run build"
  publish = "out"
  functions = "api"

[[plugins]]
  package = "@netlify/plugin-nextjs"