# Use a lightweight Python image
FROM python:3.10-slim

# Set working directory in the container
WORKDIR /usr/src/app

# Copy any necessary setup files (optional)
# COPY requirements.txt ./
# RUN pip install --no-cache-dir -r requirements.txt

# Command to run the code when the container starts
CMD ["python3", "main.py"]